version: "3.8"
services: 
    # authdb:
    #     container_name: authdb
    #     restart: always
    #     ports: 
    #         - "1433:1433"
    #     volumes:
    #         - authdb_volume:/var/opt/mssql
    #     environment: 
    #         - ACCEPT_EULA=Y
    #         - SA_PASSWORD=admin
    guidedb: 
        container_name: guidedb
        restart: always
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=PhoneGuide
    # reportdb: 
    #     container_name: reportdb
    #     restart: always
    #     ports: 
    #         - "5432:5432"
    #     environment: 
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=admin
    #         - POSTGRES_DB=PhoneReport   
    rabbitmq: 
        container_name: rabbitmq
        restart: always
        ports: 
            - "5672:5672"
            - "15672:15672"
    guide.api:
        container_name: guide.api
        environment: 
            - ASPNETCORE_ENVIROENMENT=Development
            - Rabbitmq:Url=rabbitmq
            - "ConnectionStrings:DefaultConnection=Server=guidedb;Port=5432;Database=PhoneGuide;User Id=postgres;Password=admin;"
        ports:
            - "44337:80"
        depends_on: 
            - guidedb

    pgAdmin4:
        container_name: pgAdmin4
        restart: always
        environment: 
            - PGADMIN_DEFAULT_EMAIL=malik.masis@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
     